import {
  GAME_LIFECYCLE_EVENT_TYPE,
  TEMPLATE_FIELD_TYPE,
  UI_MODULE,
  type TemplateSchema,
} from "@mashedgames/shared";

export const luckyWheelManifest = {
  templateId: "lucky-wheel",
  version: "1.0.0",
  displayName: "Lucky Wheel",
  lockedFields: ["activeTemplateId", "schemaVersion"],
  supportsUI: [UI_MODULE.LEAD_CAPTURE],
  supportedEvents: [
    GAME_LIFECYCLE_EVENT_TYPE.ON_GAME_READY,
    GAME_LIFECYCLE_EVENT_TYPE.ON_GAME_START,
    GAME_LIFECYCLE_EVENT_TYPE.ON_SCORE_UPDATE,
    GAME_LIFECYCLE_EVENT_TYPE.ON_GAME_OVER,
  ],
  assetRestrictions: [
    {
      key: "wheel-pointer",
      label: "Pointer",
      allowedFormats: ["png", "webp"],
      dimensions: { width: 64, height: 64, strict: false },
    },
    {
      key: "wheel-center",
      label: "Spin button",
      allowedFormats: ["png", "webp"],
      dimensions: { width: 120, height: 120, strict: false },
    },
    {
      key: "wheel-rim",
      label: "Wheel rim",
      allowedFormats: ["png", "webp"],
      dimensions: { width: 512, height: 512, strict: false },
    },
  ],
  fields: [
    {
      key: "segmentCount",
      type: TEMPLATE_FIELD_TYPE.NUMBER,
      label: "Number of segments",
      group: "prizeTable",
      min: 4,
      max: 8,
      step: 1,
      default: 8,
    },
    {
      key: "prize1Name",
      type: TEMPLATE_FIELD_TYPE.TEXT,
      label: "Name (shown on wheel)",
      group: "prizeTable/prize-1",
      default: "10% Off",
    },
    {
      key: "prize1Weight",
      type: TEMPLATE_FIELD_TYPE.NUMBER,
      label: "Likelihood (higher wins more often)",
      group: "prizeTable/prize-1",
      min: 1,
      max: 100,
      step: 1,
      default: 20,
    },
    {
      key: "prize1Value",
      type: TEMPLATE_FIELD_TYPE.NUMBER,
      label: "Value (0 = instant retry, no lead form)",
      group: "prizeTable/prize-1",
      min: 0,
      max: 9999,
      step: 1,
      default: 10,
    },
    {
      key: "prize2Name",
      type: TEMPLATE_FIELD_TYPE.TEXT,
      label: "Name (shown on wheel)",
      group: "prizeTable/prize-2",
      default: "Free Shipping",
    },
    {
      key: "prize2Weight",
      type: TEMPLATE_FIELD_TYPE.NUMBER,
      label: "Likelihood (higher wins more often)",
      group: "prizeTable/prize-2",
      min: 1,
      max: 100,
      step: 1,
      default: 20,
    },
    {
      key: "prize2Value",
      type: TEMPLATE_FIELD_TYPE.NUMBER,
      label: "Value (0 = instant retry, no lead form)",
      group: "prizeTable/prize-2",
      min: 0,
      max: 9999,
      step: 1,
      default: 10,
    },
    {
      key: "prize3Name",
      type: TEMPLATE_FIELD_TYPE.TEXT,
      label: "Name (shown on wheel)",
      group: "prizeTable/prize-3",
      default: "Try Again",
    },
    {
      key: "prize3Weight",
      type: TEMPLATE_FIELD_TYPE.NUMBER,
      label: "Likelihood (higher wins more often)",
      group: "prizeTable/prize-3",
      min: 1,
      max: 100,
      step: 1,
      default: 20,
    },
    {
      key: "prize3Value",
      type: TEMPLATE_FIELD_TYPE.NUMBER,
      label: "Value (0 = instant retry, no lead form)",
      group: "prizeTable/prize-3",
      min: 0,
      max: 9999,
      step: 1,
      default: 0,
    },
    {
      key: "prize4Name",
      type: TEMPLATE_FIELD_TYPE.TEXT,
      label: "Name (shown on wheel)",
      group: "prizeTable/prize-4",
      default: "20% Off",
    },
    {
      key: "prize4Weight",
      type: TEMPLATE_FIELD_TYPE.NUMBER,
      label: "Likelihood (higher wins more often)",
      group: "prizeTable/prize-4",
      min: 1,
      max: 100,
      step: 1,
      default: 10,
    },
    {
      key: "prize4Value",
      type: TEMPLATE_FIELD_TYPE.NUMBER,
      label: "Value (0 = instant retry, no lead form)",
      group: "prizeTable/prize-4",
      min: 0,
      max: 9999,
      step: 1,
      default: 20,
    },
    {
      key: "prize5Name",
      type: TEMPLATE_FIELD_TYPE.TEXT,
      label: "Name (shown on wheel)",
      group: "prizeTable/prize-5",
      default: "Free Gift",
    },
    {
      key: "prize5Weight",
      type: TEMPLATE_FIELD_TYPE.NUMBER,
      label: "Likelihood (higher wins more often)",
      group: "prizeTable/prize-5",
      min: 1,
      max: 100,
      step: 1,
      default: 10,
    },
    {
      key: "prize5Value",
      type: TEMPLATE_FIELD_TYPE.NUMBER,
      label: "Value (0 = instant retry, no lead form)",
      group: "prizeTable/prize-5",
      min: 0,
      max: 9999,
      step: 1,
      default: 15,
    },
    {
      key: "prize6Name",
      type: TEMPLATE_FIELD_TYPE.TEXT,
      label: "Name (shown on wheel)",
      group: "prizeTable/prize-6",
      default: "5% Off",
    },
    {
      key: "prize6Weight",
      type: TEMPLATE_FIELD_TYPE.NUMBER,
      label: "Likelihood (higher wins more often)",
      group: "prizeTable/prize-6",
      min: 1,
      max: 100,
      step: 1,
      default: 10,
    },
    {
      key: "prize6Value",
      type: TEMPLATE_FIELD_TYPE.NUMBER,
      label: "Value (0 = instant retry, no lead form)",
      group: "prizeTable/prize-6",
      min: 0,
      max: 9999,
      step: 1,
      default: 5,
    },
    {
      key: "prize7Name",
      type: TEMPLATE_FIELD_TYPE.TEXT,
      label: "Name (shown on wheel)",
      group: "prizeTable/prize-7",
      default: "Grand Prize",
    },
    {
      key: "prize7Weight",
      type: TEMPLATE_FIELD_TYPE.NUMBER,
      label: "Likelihood (higher wins more often)",
      group: "prizeTable/prize-7",
      min: 1,
      max: 100,
      step: 1,
      default: 5,
    },
    {
      key: "prize7Value",
      type: TEMPLATE_FIELD_TYPE.NUMBER,
      label: "Value (0 = instant retry, no lead form)",
      group: "prizeTable/prize-7",
      min: 0,
      max: 9999,
      step: 1,
      default: 100,
    },
    {
      key: "prize8Name",
      type: TEMPLATE_FIELD_TYPE.TEXT,
      label: "Name (shown on wheel)",
      group: "prizeTable/prize-8",
      default: "Try Again",
    },
    {
      key: "prize8Weight",
      type: TEMPLATE_FIELD_TYPE.NUMBER,
      label: "Likelihood (higher wins more often)",
      group: "prizeTable/prize-8",
      min: 1,
      max: 100,
      step: 1,
      default: 5,
    },
    {
      key: "prize8Value",
      type: TEMPLATE_FIELD_TYPE.NUMBER,
      label: "Value (0 = instant retry, no lead form)",
      group: "prizeTable/prize-8",
      min: 0,
      max: 9999,
      step: 1,
      default: 0,
    },
    {
      key: "showSegmentLabels",
      type: TEMPLATE_FIELD_TYPE.TOGGLE,
      label: "Show prize names on wheel",
      group: "wheelSetup",
      default: true,
    },
    {
      key: "labelFontSizePercent",
      type: TEMPLATE_FIELD_TYPE.SLIDER,
      label: "Prize label text size (% of wheel radius)",
      group: "wheelSetup",
      min: 6,
      max: 20,
      step: 1,
      default: 11,
    },
    {
      key: "labelTextColor",
      type: TEMPLATE_FIELD_TYPE.COLOR,
      label: "Prize label text color",
      group: "wheelSetup",
      default: "#ffffff",
    },
    {
      key: "spinDurationMs",
      type: TEMPLATE_FIELD_TYPE.NUMBER,
      label: "Spin duration (ms)",
      group: "spinBehavior",
      min: 1500,
      max: 8000,
      step: 100,
      default: 4500,
    },
    {
      key: "minFullRotations",
      type: TEMPLATE_FIELD_TYPE.NUMBER,
      label: "Minimum full rotations",
      group: "spinBehavior",
      min: 2,
      max: 10,
      step: 1,
      default: 4,
    },
    {
      key: "wheelRadiusPercent",
      type: TEMPLATE_FIELD_TYPE.SLIDER,
      label: "Wheel size (% of viewport)",
      group: "spinBehavior",
      min: 24,
      max: 48,
      step: 1,
      default: 38,
    },
    {
      key: "logoSizePercent",
      type: TEMPLATE_FIELD_TYPE.SLIDER,
      label: "Logo size (% of wheel radius)",
      group: "branding",
      min: 10,
      max: 100,
      step: 1,
      default: 42,
    },
    {
      key: "spinButtonLabel",
      type: TEMPLATE_FIELD_TYPE.TEXT,
      label: "Button text",
      group: "spinButton",
      default: "Spin",
    },
    {
      key: "spinButtonColor",
      type: TEMPLATE_FIELD_TYPE.COLOR,
      label: "Button color",
      group: "spinButton",
      default: "#6366f1",
    },
    {
      key: "spinButtonHighlightColor",
      type: TEMPLATE_FIELD_TYPE.COLOR,
      label: "Button highlight color",
      group: "spinButton",
      default: "#818cf8",
    },
    {
      key: "spinButtonBorderColor",
      type: TEMPLATE_FIELD_TYPE.COLOR,
      label: "Button border color",
      group: "spinButton",
      default: "#ffffff",
    },
    {
      key: "spinButtonTextColor",
      type: TEMPLATE_FIELD_TYPE.COLOR,
      label: "Button text color",
      group: "spinButton",
      default: "#ffffff",
    },
    {
      key: "spinButtonLabelBold",
      type: TEMPLATE_FIELD_TYPE.TOGGLE,
      label: "Bold button text",
      group: "spinButton",
      default: true,
    },
    {
      key: "spinButtonLabelItalic",
      type: TEMPLATE_FIELD_TYPE.TOGGLE,
      label: "Italic button text",
      group: "spinButton",
      default: false,
    },
    {
      key: "spinButtonLabelUnderline",
      type: TEMPLATE_FIELD_TYPE.TOGGLE,
      label: "Underline button text",
      group: "spinButton",
      default: false,
    },
    {
      key: "spinButtonFontSizePercent",
      type: TEMPLATE_FIELD_TYPE.SLIDER,
      label: "Button text size (% of button height)",
      group: "spinButton",
      min: 28,
      max: 56,
      step: 1,
      default: 42,
    },
    {
      key: "spinButtonWidthPercent",
      type: TEMPLATE_FIELD_TYPE.SLIDER,
      label: "Button width (% of wheel radius)",
      group: "spinButton",
      min: 90,
      max: 150,
      step: 1,
      default: 115,
    },
    {
      key: "centerButtonUrl",
      type: TEMPLATE_FIELD_TYPE.IMAGE,
      label: "Custom button image (optional)",
      group: "spinButton",
      textureKey: "wheel-center",
      default: "",
    },
    {
      key: "pointerUrl",
      type: TEMPLATE_FIELD_TYPE.IMAGE,
      label: "Pointer",
      group: "gameSprites",
      textureKey: "wheel-pointer",
      default: "",
    },
    {
      key: "wheelRimUrl",
      type: TEMPLATE_FIELD_TYPE.IMAGE,
      label: "Wheel rim",
      group: "gameSprites",
      textureKey: "wheel-rim",
      default: "",
    },
  ],
} satisfies TemplateSchema;

export type LuckyWheelManifest = typeof luckyWheelManifest;
