/**
 * Creates a fully self-contained staging directory for electron-builder by:
 *   1. Running `pnpm deploy --legacy --prod --node-linker=hoisted` → flat,
 *      symlink-free node_modules (no pnpm virtual store, no .pnpm directory).
 *   2. Copying every desktop source file + the pre-generated NSIS resources
 *      into the staging dir so electron-builder can run with --projectDir.
 *   3. Verifying that key runtime modules resolve before invoking packaging.
 *   4. Running electron-builder and moving output to apps/desktop/dist/.
 *
 * Using --node-linker=hoisted avoids the pnpm virtual store (.pnpm/) entirely,
 * which ensures electron-builder's asar packager sees a conventional flat
 * node_modules layout and reliably captures every transitive dependency
 * (including is-stream, which is a transitive dep of archiver-utils).
 *
 * The prebuild order must be:
 *   ensure-dist-writable → sync-installer-* → apply-nsis-* → materialize-deps
 * so that nsis/ is fully populated before we copy it into staging.
 */
import { execFileSync } from "node:child_process";
import {
  cpSync,
  rmSync,
  existsSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";

const __dirname = dirname(fileURLToPath(import.meta.url));
const desktopDir = join(__dirname, "..");
const workspaceRoot = join(desktopDir, "..", "..");
const stagingDir = join(desktopDir, "_staging_probe");
const distDir = join(desktopDir, "dist");

const requireFromStaging = createRequire(join(stagingDir, "package.json"));

function logPhase(message) {
  console.log(`[materialize-deps] ${message}`);
}

function runCommand(command, args, options = {}) {
  execFileSync(command, args, {
    stdio: "inherit",
    shell: true,
    ...options,
  });
}

function runDeploy() {
  // --legacy:            workspace does not have inject-workspace-packages=true.
  // --node-linker=hoisted: produce a flat node_modules (no .pnpm virtual store)
  //                        so electron-builder's asar sees standard CJS resolution.
  runCommand(
    "pnpm",
    [
      "deploy",
      "--filter=desktop",
      "--prod",
      "--legacy",
      "--config.node-linker=hoisted",
      stagingDir,
    ],
    {
      cwd: workspaceRoot,
      env: { ...process.env, CI: "true" },
    }
  );
}

function assertPathExists(path, description) {
  if (!existsSync(path)) {
    throw new Error(`${description} not found: ${path}`);
  }
}

function assertResolvable(moduleName) {
  try {
    requireFromStaging.resolve(moduleName);
  } catch (error) {
    throw new Error(
      `required runtime module "${moduleName}" is missing in staging. ` +
        "Check pnpm deploy output and production dependency declarations.",
      { cause: error }
    );
  }
}

function verifyStagingRuntime() {
  assertPathExists(join(stagingDir, "node_modules"), "staging node_modules");

  // Verify direct runtime dependencies are present and resolvable.
  for (const moduleName of ["archiver", "archiver-utils", "is-stream"]) {
    assertResolvable(moduleName);
  }

  // Smoke-import the module that originally triggered the is-stream crash.
  try {
    requireFromStaging("./export-ipc-utils.js");
  } catch (error) {
    throw new Error(
      "runtime smoke import failed for export-ipc-utils.js from staging.",
      { cause: error }
    );
  }
}

try {
  // ── 1. Clean & deploy all prod deps into staging ─────────────────────────
  logPhase(`creating ephemeral staging workspace at ${stagingDir}`);
  if (existsSync(stagingDir)) {
    rmSync(stagingDir, { recursive: true, force: true });
  }

  logPhase("phase deploy: running pnpm deploy (hoisted)...");
  runDeploy();

  // ── 2. Copy desktop source files into staging ────────────────────────────
  const SOURCE_FILES = [
    "main.js",
    "preload.js",
    "constants.js",
    "asset-ipc-utils.js",
    "auth-ipc-utils.js",
    "license-ipc-utils.js",
    "store-ipc-utils.js",
    "export-ipc-utils.js",
    "flat-config-ipc-utils.js",
    "admin-ipc-utils.js",
    "updater-ipc-utils.js",
    "template-update-ipc-utils.js",
    "splash.html",
    "splash-logo.png",
    "package.json",
    "runtime-supabase.json",
  ];

  logPhase("phase stage-files: copying desktop source files...");
  for (const file of SOURCE_FILES) {
    const src = join(desktopDir, file);
    if (existsSync(src)) cpSync(src, join(stagingDir, file), { force: true });
  }

  // ── 3. Copy NSIS build resources (pre-generated by sync-installer-* scripts)
  logPhase("phase stage-nsis: copying nsis build resources...");
  cpSync(join(desktopDir, "nsis"), join(stagingDir, "nsis"), {
    recursive: true,
    force: true,
  });

  // ── 4. Patch staging package.json: fix extraResources absolute path ───────
  // When electron-builder runs from _staging, relative paths like
  // "../dashboard/.next/standalone" resolve to apps/desktop/dashboard (wrong).
  // We rewrite the staging package.json to use the real absolute path.
  logPhase("phase patch-config: patching staging package.json paths...");
  const stagingPkgPath = join(stagingDir, "package.json");
  const stagingPkg = JSON.parse(readFileSync(stagingPkgPath, "utf8"));
  const standaloneAbsPath = join(
    workspaceRoot,
    "apps",
    "dashboard",
    ".next",
    "standalone"
  ).replace(/\\/g, "/");
  if (stagingPkg.build?.extraResources) {
    for (const res of stagingPkg.build.extraResources) {
      if (res.from && res.from.includes("dashboard")) {
        res.from = standaloneAbsPath;
      }
    }
  }
  writeFileSync(stagingPkgPath, JSON.stringify(stagingPkg, null, 2));

  // ── 5. Verify staging dependencies before packaging ───────────────────────
  logPhase("phase verify-runtime: validating staging dependencies...");
  verifyStagingRuntime();

  // ── 6. Run electron-builder from staging, output → apps/desktop/dist ─────
  logPhase("phase package: running electron-builder from staging...");
  runCommand(
    "npx",
    [
      "electron-builder",
      "--projectDir",
      stagingDir,
      `--config.directories.output=${distDir}`,
      "--config.directories.buildResources=nsis",
    ],
    {
      cwd: desktopDir,
      // Forward env so electron-builder can expand ${env.MASHED_UPDATE_BASE_URL}
      // and other build-time vars that the parent build-release.mjs injected.
      env: { ...process.env },
    }
  );
  logPhase("done — installer written to apps/desktop/dist/");
} finally {
  if (existsSync(stagingDir)) {
    rmSync(stagingDir, { recursive: true, force: true });
    logPhase("cleanup: removed ephemeral staging workspace.");
  }
}
