#!/usr/bin/env node
/**
 * Scans packages/templates/src/ for manifest.ts files and generates a static
 * template registry file consumed by apps/game-engine at build time.
 *
 * Templates live in a flat structure: packages/templates/src/{templateId}/
 * Each template directory must contain a manifest.ts to be included.
 *
 * Output: apps/game-engine/src/game/template-registry.generated.ts
 */
import { existsSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const gameEngineRoot = path.resolve(scriptDir, "..");
const monorepoRoot = path.resolve(gameEngineRoot, "../..");
const templatesRoot = path.resolve(monorepoRoot, "packages/templates/src");
const outputDir = path.join(gameEngineRoot, "src", "game");
const outputPath = path.join(outputDir, "template-registry.generated.ts");

/** Directories inside packages/templates/src that are not template folders. */
const SKIP_DIRS = new Set(["node_modules", ".git", "dist"]);

function listTemplateIds(): string[] {
  if (!existsSync(templatesRoot)) return [];

  return readdirSync(templatesRoot, { withFileTypes: true })
    .filter(
      (entry) =>
        entry.isDirectory() &&
        !SKIP_DIRS.has(entry.name) &&
        existsSync(path.join(templatesRoot, entry.name, "manifest.ts")),
    )
    .map((entry) => entry.name)
    .sort();
}

function buildRegistrySource(templateIds: string[]): string {
  const caseLines = templateIds
    .map(
      (id) =>
        `  "${id}": async () => {\n` +
        `    const { ${toPascalCase(id)}Scene } = await import("@mashedgames/templates");\n` +
        `    return ${toPascalCase(id)}Scene;\n` +
        `  },`,
    )
    .join("\n");

  return `/* eslint-disable */
// AUTO-GENERATED by apps/game-engine/scripts/sync-manifest-registry.ts — do not edit.
// Re-run with: pnpm sync-manifest-registry (inside apps/game-engine)
import type Phaser from "phaser";
import { MainScene } from "./scenes/MainScene.ts";

const LAZY_SCENE_REGISTRY: Record<string, () => Promise<Phaser.Types.Scenes.SceneType>> = {
${caseLines}
};

export async function resolveTemplateScene(
  templateId: string,
): Promise<Phaser.Types.Scenes.SceneType> {
  const factory = LAZY_SCENE_REGISTRY[templateId];
  if (factory) return factory();
  return MainScene;
}
`;
}

function toPascalCase(id: string): string {
  return id
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function main(): void {
  const templateIds = listTemplateIds();

  if (!existsSync(outputDir)) {
    mkdirSync(outputDir, { recursive: true });
  }

  writeFileSync(outputPath, buildRegistrySource(templateIds), "utf8");
  console.log(
    `Wrote template registry (${templateIds.length} template${templateIds.length !== 1 ? "s" : ""}: ${templateIds.join(", ") || "(none)"})`,
  );
  console.log(`  → ${outputPath}`);
}

main();
