import {
  GAME_LIFECYCLE_EVENT_TYPE,
  TEMPLATE_FIELD_TYPE,
  UI_MODULE,
  type TemplateFieldDescriptor,
  type TemplateSchema,
} from "@mashedgames/shared";

const catchGameFields: TemplateFieldDescriptor[] = [
  {
    key: "playerCatcherUrl",
    type: TEMPLATE_FIELD_TYPE.IMAGE,
    label: "Catcher",
    group: "gameSprites",
    textureKey: "player-catcher",
    default: "",
  },
  {
    key: "collectibleGoodUrl",
    type: TEMPLATE_FIELD_TYPE.IMAGE,
    label: "Good collectible",
    group: "gameSprites",
    textureKey: "collectible-good",
    default: "",
  },
  {
    key: "collectibleBadUrl",
    type: TEMPLATE_FIELD_TYPE.IMAGE,
    label: "Bad collectible",
    group: "gameSprites",
    textureKey: "collectible-bad",
    default: "",
  },
  {
    key: "goodItemPoints",
    type: TEMPLATE_FIELD_TYPE.NUMBER,
    label: "Good item points",
    group: "goodCollectibles",
    min: 1,
    max: 100,
    step: 1,
    default: 10,
  },
  {
    key: "spawnIntervalMs",
    type: TEMPLATE_FIELD_TYPE.NUMBER,
    label: "Spawn interval (ms)",
    group: "goodCollectibles",
    min: 300,
    max: 3000,
    step: 50,
    default: 900,
  },
  {
    key: "minSpawnIntervalMs",
    type: TEMPLATE_FIELD_TYPE.NUMBER,
    label: "Fastest spawn (ms)",
    group: "goodCollectibles",
    min: 150,
    max: 2000,
    step: 50,
    default: 420,
  },
  {
    key: "fallSpeedStart",
    type: TEMPLATE_FIELD_TYPE.NUMBER,
    label: "Fall speed start",
    group: "goodCollectibles",
    min: 80,
    max: 400,
    step: 10,
    default: 150,
  },
  {
    key: "fallSpeedMax",
    type: TEMPLATE_FIELD_TYPE.NUMBER,
    label: "Fall speed max",
    group: "goodCollectibles",
    min: 120,
    max: 700,
    step: 10,
    default: 280,
  },
  {
    key: "badItemPenalty",
    type: TEMPLATE_FIELD_TYPE.NUMBER,
    label: "Penalty points",
    group: "badCollectibles",
    min: 0,
    max: 50,
    step: 1,
    default: 5,
  },
  {
    key: "badItemChancePercent",
    type: TEMPLATE_FIELD_TYPE.SLIDER,
    label: "Bad item chance (%)",
    group: "badCollectibles",
    min: 0,
    max: 100,
    step: 1,
    default: 25,
  },
  {
    key: "badSpawnIntervalMs",
    type: TEMPLATE_FIELD_TYPE.NUMBER,
    label: "Spawn interval (ms)",
    group: "badCollectibles",
    min: 300,
    max: 5000,
    step: 50,
    default: 1800,
  },
  {
    key: "badMinSpawnIntervalMs",
    type: TEMPLATE_FIELD_TYPE.NUMBER,
    label: "Fastest spawn (ms)",
    group: "badCollectibles",
    min: 150,
    max: 3000,
    step: 50,
    default: 900,
  },
  {
    key: "badFallSpeedStart",
    type: TEMPLATE_FIELD_TYPE.NUMBER,
    label: "Fall speed start",
    group: "badCollectibles",
    min: 80,
    max: 400,
    step: 10,
    default: 130,
  },
  {
    key: "badFallSpeedMax",
    type: TEMPLATE_FIELD_TYPE.NUMBER,
    label: "Fall speed max",
    group: "badCollectibles",
    min: 120,
    max: 700,
    step: 10,
    default: 260,
  },
];

export const catchGameManifest = {
  templateId: "catch-game",
  version: "2.0.0",
  displayName: "Catch Game",
  lockedFields: ["activeTemplateId", "schemaVersion"],
  supportsUI: [UI_MODULE.HIGHSCORE, UI_MODULE.COUNTDOWN_TIMER],
  supportedEvents: [
    GAME_LIFECYCLE_EVENT_TYPE.ON_GAME_READY,
    GAME_LIFECYCLE_EVENT_TYPE.ON_GAME_START,
    GAME_LIFECYCLE_EVENT_TYPE.ON_SCORE_UPDATE,
    GAME_LIFECYCLE_EVENT_TYPE.ON_TIMER_UPDATE,
    GAME_LIFECYCLE_EVENT_TYPE.ON_GAME_OVER,
  ],
  assetRestrictions: [
    {
      key: "player-catcher",
      label: "Catcher",
      allowedFormats: ["png", "webp"],
      dimensions: { width: 120, height: 40, strict: false },
    },
    {
      key: "collectible-good",
      label: "Good collectible",
      allowedFormats: ["png", "webp"],
      dimensions: { width: 48, height: 48, strict: false },
    },
    {
      key: "collectible-bad",
      label: "Bad collectible",
      allowedFormats: ["png", "webp"],
      dimensions: { width: 48, height: 48, strict: false },
    },
  ],
  fields: catchGameFields,
} satisfies TemplateSchema;

export type CatchGameManifest = typeof catchGameManifest;
